Repository Thaynara-Andrade/Deleite, pull requests merged in 2023-09, with the labels that each got.

#1 :sparkles: feat - Tutorial View
  Deleite.xcodeproj/project.pbxproj
  Deleite.xcodeproj/project.xcworkspace/xcuserdata/maahdisousa.xcuserdatad/UserInterfaceState.xcuserstate
  Deleite.xcodeproj/xcshareddata/xcschemes/Deleite.xcscheme
  Deleite.xcodeproj/xcuserdata/maahdisousa.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Deleite.xcodeproj/xcuserdata/maahdisousa.xcuserdatad/xcschemes/xcschememanagement.plist
  Deleite/Components/ButtonBackView.swift
  Deleite/Components/MenuButtonView.swift
  Deleite/DeleiteApp.swift
  Deleite/TutorialView.swift
  DeleiteUITests/Assets.xcassets/AccentColor.colorset/Contents.json
  DeleiteUITests/Assets.xcassets/AppIcon.appiconset/Contents.json
  DeleiteUITests/Assets.xcassets/Contents.json
Labels: enhancement

#3 Feat/homescreenview
  Deleite.xcodeproj/project.pbxproj
  Deleite.xcodeproj/xcuserdata/thaynaraandrade.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Deleite/AgendamentoView.swift
  Deleite/ContentView.swift
  Deleite/DeleiteApp.swift
  Deleite/Homescreen.swift
  Deleite/MilkbankView.swift
  Deleite/QuestionsView.swift
  Deleite/SchedulingView.swift
Labels: enhancement

#7 Tutorial view
  .gitignore
  Deleite.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Deleite.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Deleite.xcodeproj/project.xcworkspace/xcuserdata/maahdisousa.xcuserdatad/UserInterfaceState.xcuserstate
  Deleite.xcodeproj/xcuserdata/maahdisousa.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Deleite.xcodeproj/xcuserdata/maahdisousa.xcuserdatad/xcschemes/xcschememanagement.plist
  Deleite.xcodeproj/xcuserdata/thaynaraandrade.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Deleite.xcodeproj/xcuserdata/thaynaraandrade.xcuserdatad/xcschemes/xcschememanagement.plist
  Deleite/Components/MenuButtonView.swift
  Deleite/DeleiteApp.swift
  Deleite/TutorialView.swift
Labels: bug

#8 Develop
  .gitignore
  Deleite.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Deleite.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Deleite.xcodeproj/project.xcworkspace/xcuserdata/maahdisousa.xcuserdatad/UserInterfaceState.xcuserstate
  Deleite.xcodeproj/xcuserdata/maahdisousa.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Deleite.xcodeproj/xcuserdata/maahdisousa.xcuserdatad/xcschemes/xcschememanagement.plist
  Deleite.xcodeproj/xcuserdata/thaynaraandrade.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Deleite.xcodeproj/xcuserdata/thaynaraandrade.xcuserdatad/xcschemes/xcschememanagement.plist
  Deleite/Components/MenuButtonView.swift
  Deleite/DeleiteApp.swift
  Deleite/TutorialView.swift
Labels: bug

#9 :sparkless: removed view
  Deleite.xcodeproj/project.pbxproj
  Deleite/Homescreen.swift
  Deleite/MapBancosView.swift
  Deleite/MilkbankView.swift
Labels: enhancement

#11 :sparkles: Homescreen colors
  Deleite/Homescreen.swift
  Deleite/SchedulingView.swift
  DeleiteUITests/Assets.xcassets/Button-Color.colorset/Contents.json
  DeleiteUITests/Assets.xcassets/Buttonvariable-Color.colorset/Contents.json
  DeleiteUITests/Assets.xcassets/Text-Color.colorset/Contents.json
Labels: enhancement

#12 :sparkless: Atualização de assets
  Deleite.xcodeproj/project.pbxproj
  Deleite/CarouselTutorial.swift
  Deleite/Components/ImageCard.swift
  Deleite/Components/ImageCards.swift
  Deleite/Components/MenuButtonView.swift
  Deleite/Components/MenuButtons.swift
  Deleite/ContentView.swift
  Deleite/DeleiteApp.swift
  Deleite/TutorialView.swift
  DeleiteUITests/Assets.xcassets/mama.imageset/Contents.json
  DeleiteUITests/Assets.xcassets/mama.imageset/beneficios-amamentacao-mae-bebe-1024x683.jpeg
Labels: enhancement

#13 :sparkles: Tela menu tutorial
  Deleite.xcodeproj/project.pbxproj
  Deleite/Components/ImageCard.swift
  Deleite/Components/MenuButtonView.swift
  Deleite/Components/MenuButtons.swift
  Deleite/TutorialView.swift
Labels: enhancement

#14 Feat/homescreenview
  Deleite.xcodeproj/project.pbxproj
  Deleite/Components/HomeButton.swift
  Deleite/DeleiteApp.swift
  Deleite/Homescreen.swift
  Deleite/HomescreenView.swift
  Deleite/WebView.swift
  DeleiteUITests/Assets.xcassets/Hospital.imageset/Contents.json
  DeleiteUITests/Assets.xcassets/Hospital.imageset/Hospital.png
  DeleiteUITests/Assets.xcassets/Tutorial.imageset/Contents.json
  DeleiteUITests/Assets.xcassets/Tutorial.imageset/Tutorial.png
Labels: bug, enhancement

#15 Creating a sheet with one click
  Deleite/DeleiteApp.swift
  Deleite/MilkbankView.swift
Labels: bug, enhancement

#16 Feat/bancodeleite
  Deleite.xcodeproj/project.pbxproj
  Deleite/DataServices/LocationsDataService.swift
  Deleite/DeleiteApp.swift
  Deleite/Homescreen.swift
  Deleite/HomescreenView.swift
  Deleite/MilkbankView.swift
  Deleite/Models/Location.swift
  Deleite/ViewModels/LocationsViewModel.swift
  Deleite/Views/LocationMapAnnotion.swift
  Deleite/Views/LocationsView.swift
Labels: enhancement

#21 Carousel tutorial coleta
  Deleite.xcodeproj/project.pbxproj
  Deleite/Assets.xcassets/TESTE-CARD.imageset/Contents.json
  Deleite/Assets.xcassets/TESTE-CARD.imageset/TESTE-CARD.svg
  Deleite/Assets.xcassets/TUTO1-SVGC.imageset/Contents.json
  Deleite/Assets.xcassets/TUTO1-SVGC.imageset/TUTO1-SVGC.svg
  Deleite/Assets.xcassets/higiene.imageset/Contents.json
  Deleite/Assets.xcassets/higiene.imageset/Group 47.png
  Deleite/Assets.xcassets/image_test.imageset/Contents.json
  Deleite/Assets.xcassets/image_test.imageset/image_test.png
  Deleite/Components/MenuButtonView.swift
  Deleite/DeleiteApp.swift
  Deleite/TutorialCollect.swift
  Deleite/TutorialSanitation.swift
  Deleite/TutorialStorege.swift
  Deleite/TutorialView.swift
Labels: enhancement

#22 Feat/questions view
  Deleite.xcodeproj/project.pbxproj
  Deleite/Assets.xcassets/Buttonvariable-Color.colorset/Contents.json
  Deleite/Assets.xcassets/Card-Armazenar/Contents.json
  Deleite/Assets.xcassets/Card-Higienização/Contents.json
  Deleite/Assets.xcassets/Card-Retirarleite/Contents.json
  Deleite/Assets.xcassets/Colors/Button-Color.colorset/Contents.json
  Deleite/Assets.xcassets/Colors/Buttonvariable-Color.colorset/Contents.json
  Deleite/Assets.xcassets/Colors/Contents.json
  Deleite/Assets.xcassets/Colors/Text-Color.colorset/Contents.json
  Deleite/Assets.xcassets/Homescreen/Agendar coleta.imageset/Contents.json
  Deleite/Assets.xcassets/Homescreen/Agendar coleta.imageset/Image.png
  Deleite/Assets.xcassets/Homescreen/Banco de leite.imageset/Contents.json
  Deleite/Assets.xcassets/Homescreen/Banco de leite.imageset/Image 2.png
  Deleite/Assets.xcassets/Homescreen/Contents.json
  Deleite/Assets.xcassets/Homescreen/Fazer doação.imageset/Contents.json
  Deleite/Assets.xcassets/Homescreen/Fazer doação.imageset/Image.png
  Deleite/Assets.xcassets/Homescreen/Perguntas frequentes.imageset/Contents.json
  Deleite/Assets.xcassets/Homescreen/Perguntas frequentes.imageset/Image 4.png
  Deleite/Assets.xcassets/Homescreen/Tutorial.imageset/Contents.json
  Deleite/Assets.xcassets/Homescreen/Tutorial.imageset/Image.png
  Deleite/Assets.xcassets/Hospital.imageset/Contents.json
  Deleite/Assets.xcassets/Hospital.imageset/Hospital.png
  Deleite/Assets.xcassets/Image.imageset/Contents.json
  Deleite/Assets.xcassets/Image.imageset/Image.png
  Deleite/Assets.xcassets/Maps/Contents.json
  Deleite/Assets.xcassets/Tutorial.imageset/Contents.json
  Deleite/Assets.xcassets/Tutorial.imageset/Tutorial.png
  Deleite/Assets.xcassets/TutorialView/Contents.json
  Deleite/Assets.xcassets/mama.imageset/Contents.json
  Deleite/Assets.xcassets/mama.imageset/beneficios-amamentacao-mae-bebe-1024x683.jpeg
  Deleite/DeleiteApp.swift
  Deleite/Homescreen.swift
  Deleite/HomescreenView.swift
  Deleite/QuestionsView.swift
Labels: enhancement

#24 Feat/questions view
  AlertView.swift
  Deleite.xcodeproj/project.pbxproj
  Deleite.xcodeproj/xcshareddata/xcschemes/Deleite.xcscheme
  Deleite/Assets.xcassets/Card-Higienização/TESTE-CARD.imageset/Contents.json
  Deleite/Assets.xcassets/Card-Higienização/TESTE-CARD.imageset/TESTE-CARD.svg
  Deleite/Assets.xcassets/Card-Higienização/TUTO1-SVGC.imageset/Contents.json
  Deleite/Assets.xcassets/Card-Higienização/TUTO1-SVGC.imageset/TUTO1-SVGC.svg
  Deleite/Assets.xcassets/Card-Higienização/image_test.imageset/Contents.json
  Deleite/Assets.xcassets/Card-Higienização/image_test.imageset/image_test.png
  Deleite/Assets.xcassets/TutorialView/Armazenamento.imageset/Contents.json
  Deleite/Assets.xcassets/TutorialView/Armazenamento.imageset/Group 87.png
  Deleite/Assets.xcassets/TutorialView/Higiene 1.imageset/Contents.json
  Deleite/Assets.xcassets/TutorialView/Higiene 1.imageset/Group 85 (1).png
  Deleite/Assets.xcassets/TutorialView/Higiene.imageset/Contents.json
  Deleite/Assets.xcassets/TutorialView/Higiene.imageset/Group 68 (2).svg
  Deleite/Assets.xcassets/TutorialView/Retirada.imageset/Contents.json
  Deleite/Assets.xcassets/TutorialView/Retirada.imageset/Group 88.png
  Deleite/Assets.xcassets/higiene.imageset/Group 47.png
  Deleite/Components/HomeButton.swift
  Deleite/Components/HomeImage.swift
  Deleite/Components/MenuButtonView.swift
  Deleite/HomescreenView.swift
  Deleite/QuestionsView.swift
  Deleite/TutorialView.swift
Labels: enhancement

#26 :sparkles: assets add
  Deleite/Assets.xcassets/Card-Armazenar/Armazenar-1.imageset/Armazenar-1.png
  Deleite/Assets.xcassets/Card-Armazenar/Armazenar-1.imageset/Contents.json
  Deleite/Assets.xcassets/Card-Armazenar/Armazenar-2.imageset/Armazenar-2.png
  Deleite/Assets.xcassets/Card-Armazenar/Armazenar-2.imageset/Contents.json
  Deleite/Assets.xcassets/Card-Armazenar/Armazenar-3.imageset/Armazenar-3.png
  Deleite/Assets.xcassets/Card-Armazenar/Armazenar-3.imageset/Contents.json
  Deleite/Assets.xcassets/Card-Armazenar/Armazenar-4.imageset/Armazenar-4.png
  Deleite/Assets.xcassets/Card-Armazenar/Armazenar-4.imageset/Contents.json
  Deleite/Assets.xcassets/Card-Armazenar/Armazenar-5.imageset/Armazenar-5.png
  Deleite/Assets.xcassets/Card-Armazenar/Armazenar-5.imageset/Contents.json
  Deleite/Assets.xcassets/Card-Retirarleite/Retirarleite-1.imageset/Contents.json
  Deleite/Assets.xcassets/Card-Retirarleite/Retirarleite-1.imageset/Retirarleite-1.png
  Deleite/Assets.xcassets/Card-Retirarleite/Retirarleite-2.imageset/Contents.json
  Deleite/Assets.xcassets/Card-Retirarleite/Retirarleite-2.imageset/Retirarleite-2.png
  Deleite/Assets.xcassets/Card-Retirarleite/Retirarleite-3.imageset/Contents.json
  Deleite/Assets.xcassets/Card-Retirarleite/Retirarleite-3.imageset/Retirarleite-3.png
  Deleite/Assets.xcassets/Card-Retirarleite/Retirarleite-4.imageset/Contents.json
  Deleite/Assets.xcassets/Card-Retirarleite/Retirarleite-4.imageset/Retirarleite-4.png
  Deleite/Assets.xcassets/Card-Retirarleite/Retirarleite-5.imageset/Contents.json
  Deleite/Assets.xcassets/Card-Retirarleite/Retirarleite-5.imageset/Retirarleite-5.png
Labels: enhancement

#30 :bug: Bug fix
  Deleite/HomescreenView.swift
  Deleite/QuestionsView.swift
Labels: enhancement
